name: repo-all
on: 
  repository_dispatch:
jobs:
  ONE:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Workflow  = "${{ github.workflow }}
          echo "Action    = "${{ github.event.action }}
          echo "Function  = "${{ toJson(github.event.client_payload.function) }}
