name: workflow_dispatch
on: 
  workflow_dispatch:
    inputs:
      p1:
        description: 'parameter'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Inputs: ${{ toJson(github.event.inputs) }}"