name: myworkflow
on: 
  workflow_dispatch:
    inputs:
      p1:
        description: 'parameter'
      fileinput:
        description: 'file content as JSON string'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump Inputs
      env:
        INPUTS: ${{ toJson(github.event.inputs) }}
      run: |
        echo "$INPUTS"
    - name: Call Script implementing foo()
      env:
        INPUTS: ${{ toJson(github.event.inputs) }}
      run: node ./handler.js "$INPUTS"
       